### ISSUE TITLE
Transfer to glslify org

### ISSUE THREAD

**Issue by dy** [glslify/glslify-require#12]
I've just discovered this transform, normalizing the cases of glslify-loader and rollup-plugin-glslify, so that can be used in the same fashion now dependless of bundler (https://github.com/glslify/glslify/issues/118).

@ericmorand would you consider the transition? That will help other glslify consumers.
I can grant you an access.

**Comment by ericmorand** [comment]
@dy, it would be fantastic! Please let me know what I need to do to transfer the project.

**Comment by dy** [comment]
https://github.com/glslify/glslify/invitations

Just sent you an invitation.
You can transfer the repo to the org.

**Comment by ericmorand** [comment]
I still have no rights to create a project on the org. I guess you only gave me rights to `glslify/glslify`, right?

**Comment by dy** [comment]
@ericmorand yep. Done!

**Comment by ericmorand** [comment]
Transfer done.
